import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const AppStyles = StyleSheet.create({
  // Container styles
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  content: {
    flex: 1,
    padding: 16,
  },
  
  // Header styles
  headerContainer: {
    backgroundColor: '#fff',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  addressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  addressText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#333',
    flex: 1,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 48,
  },
  searchIcon: {
    marginRight: 8,
    color: '#666',
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  
  // Navigation styles
  navContainer: {
    flexDirection: 'row',
    height: 70,
    backgroundColor: '#FAECE0',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    paddingBottom: 8,
  },
  tab: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
  },
  tabLabel: {
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
    color: '#666',
  },
  activeTab: {
    color: '#a0522d',
  },
  
  // Content styles
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#7F3F23',
  },
  productCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  productTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: '#333',
  },
  productPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#a0522d',
  },
  
  // Slideshow styles
  slideshowContainer: {
    marginBottom: 20,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
  },
  slide: {
    width: width - 32, // Account for padding
    height: 200,
    position: 'relative',
  },
  slideImage: {
    width: '100%',
    height: '100%',
  },
  slideTitle: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  dotsContainer: {
    position: 'absolute',
    bottom: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 4,
  },
  activeDot: {
    backgroundColor: '#a0522d',
  },
  inactiveDot: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  arrow: {
    position: 'absolute',
    top: '50%',
    marginTop: -20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftArrow: {
    left: 10,
  },
  rightArrow: {
    right: 10,
  },
  arrowText: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
  },

  // Section styles
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    // paddingHorizontal: 8,
  },
  sectionTitleWithArrow: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  arrowIcon: {
    padding: 8,
  },

  sectionContainer: {
    marginBottom: 24,
  },
  horizontalScroll: {
    paddingVertical: 8,
  },
  handicraftCard: {
    width: 150,
    marginRight: 16,
    backgroundColor: '#FAECE0',
    borderRadius: 8,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  handicraftImage: {
    width: '100%',
    height: 120,
    borderRadius: 6,
    marginBottom: 8,
  },
  handicraftTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
    color: '#333',
  },
  handicraftPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#A0522D',
  },

  // Artisan Stories
  artisanStoriesContainer: {
    marginTop: 8,
  },
  artisanCard: {
    backgroundColor: '#FAECE0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  artisanHeader: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  artisanImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    marginRight: 12,
  },
  artisanInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  artisanName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 2,
  },
  artisanCraft: {
    fontSize: 14,
    color: '#333',
    marginBottom: 2,
  },
  artisanLocation: {
    fontSize: 12,
    color: '#666',
    marginBottom: 2,
  },
  artisanYears: {
    fontSize: 12,
    color: '#888',
    fontStyle: 'italic',
  },
  artisanStory: {
    fontSize: 14,
    lineHeight: 20,
    color: '#444',
    fontStyle: 'italic',
    borderLeftWidth: 3,
    borderLeftColor: '#a0522d',
    paddingLeft: 12,
  },

  // Featured Products
  featuredProductCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  featuredProductImage: {
    width: '100%',
    height: 200,
  },
  featuredProductOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(93, 86, 86, 0.6)',
    padding: 12,
  },
  featuredProductTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  featuredProductPrice: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  horizontalProductCard: {
    width: 150,
    height: 180,
    marginRight: 16,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  horizontalProductImage: {
    width: '100%',
    height: '100%',
  },
  horizontalProductOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    padding: 8,
  },
  horizontalProductTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 2,
  },
  horizontalProductPrice: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },

  // Profile Page Styles
  profileHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  profileHeaderTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  profileContent: {
    flex: 1,
    backgroundColor: '#fff',
  },
  logoContainer: {
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  circularLogo: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#a0522d',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  logoText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
  },
  welcomeText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 16,
  },
  SignUpButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAECE0',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },
  loginText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#a0522d',
    marginRight: 8,
  },
  ordersReturnsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  orderReturnCard: {
    alignItems: 'center',
    backgroundColor: '#FAECE0',
    padding: 16,
    borderRadius: 12,
    width: '48%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  orderReturnText: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  accountSection: {
    backgroundColor: '#fff',
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  accountOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  optionText: {
    flex: 1,
    fontSize: 16,
    color: '#a0522d',
    marginLeft: 16,
  },

  // Login/Signup Page Styles
  signupButton: {
    backgroundColor: '#a0522d',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 24,
  },
  signupButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#ddd',
  },
  dividerText: {
    marginHorizontal: 10,
    color: '#666',
    fontWeight: '600',
  },

  // Login/Signup Page Styles
  loginHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    backgroundColor: '#fff',
  },
  backButton: {
    padding: 8,
  },
  appName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  placeholder: {
    width: 40, // Same as back button for balanced spacing
  },
  loginContent: {
    flex: 1,
    padding: 16,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#FAECE0',
    borderRadius: 8,
    marginBottom: 24,
    padding: 4,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTabButton: {
    backgroundColor: '#a0522d',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  tabButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#a0525d',
  },
  activeTabButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  tabButtonHorizontal: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: '#fff',
    marginHorizontal: 6,
    minWidth: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTabButtonHorizontal: {
    // backgroundColor: '#a0522d',
    borderBottomColor: '#a0522d',
    borderBottomWidth: 3,
    
  },
  tabButtonTextHorizontal: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
  },
  activeTabButtonTextHorizontal: {
    color: '#a0522d',
    fontWeight: '600',
  },
  
  // Form Styles
  formContainer: {
    marginBottom: 24,
  },
  labelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 10,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#fff',
    marginBottom: 16,
  },

  // LoginForm Styles
  formTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  otpMethodContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 16,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#a0522d',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  radioChecked: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#a0522d',
  },
  radioLabel: {
    fontSize: 14,
    color: '#333',
  },
  otpContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  otpInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    marginRight: 12,
  },
  getOtpButton: {
    backgroundColor: '#a0522d',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  getOtpText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  loginButton: {
    backgroundColor: '#a0522d',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 16,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#a0522d',
    backgroundColor: '#fff',
  },
  googleIcon: {
    width: 24,
    height: 24,
    marginRight: 12,
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
  },
  optionIcon: {
    marginLeft: 4,
  },

  // Terms and conditions styles
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#a0522d',
    backgroundColor: '#fff',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  termsText: {
    fontSize: 14,
    color: '#333',
    flex: 1,
    flexWrap: 'wrap',
  },
  termsLink: {
    color: '#a0522d',
    fontWeight: '500',
  },
  disabledButton: {
    backgroundColor: '#ccc',
    opacity: 0.7,
  },

  // Calendar Styles
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  calendarWeekdays: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
  },
  calendarDays: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  calendarDay: {
    width: '14.28%', // 7 days in a week
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 2,
  },
  selected: {
    backgroundColor: '#a0522d',
    borderRadius: 20,
  },
  empty: {
    backgroundColor: 'transparent',
  },

  // Product Detail Page Styles
  productImageContainer: {
    backgroundColor: '#fff',
    paddingBottom: 16,
  },
  productMainImage: {
    width: width,
    height: width,
  },
  productThumbnailContainer: {
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  productThumbnail: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  productSelectedThumbnail: {
    borderColor: '#a0522d',
  },
  productThumbnailImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
  },
  productDetailsContainer: {
    backgroundColor: '#fff',
    padding: 16,
    marginTop: 8,
  },
  productName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  productRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  productRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#388e3c',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginRight: 8,
  },
  productRatingText: {
    fontSize: 12,
    color: '#fff',
    marginRight: 4,
    fontWeight: 'bold',
  },
  productReviewText: {
    fontSize: 14,
    color: '#666',
    marginRight: 12,
  },
  productSoldText: {
    fontSize: 14,
    color: '#666',
  },
  productPrice: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#a0522d',
    marginBottom: 20,
  },
  productSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
    marginTop: 8,
  },
  productDescription: {
    fontSize: 16,
    color: '#555',
    lineHeight: 24,
    marginBottom: 16,
  },
  productArtisanContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  productArtisanImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 12,
  },
  productArtisanInfo: {
    flex: 1,
  },
  productArtisanName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  productArtisanLocation: {
    fontSize: 14,
    color: '#666',
    marginBottom: 2,
  },
  productArtisanYears: {
    fontSize: 12,
    color: '#888',
    fontStyle: 'italic',
  },
  productQuantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  productQuantityButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
  },
  productQuantityText: {
    fontSize: 18,
    fontWeight: '600',
    marginHorizontal: 16,
    minWidth: 30,
    textAlign: 'center',
  },
  productFooter: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  productCartButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#a0522d',
    marginRight: 12,
  },
  productCartButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#a0522d',
    marginLeft: 8,
  },
  productBuyButton: {
    flex: 1,
    backgroundColor: '#a0522d',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  productBuyButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  authenticityBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#388e3c',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
  },
  authenticityText: {
    color: '#fff',
    fontSize: 12,
    marginLeft: 5,
    fontWeight: '500',
  },
  
  // Product Options
  productOptionsContainer: {
    flexDirection: 'row',
    marginBottom: 15,
  },
  colorOption: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eee',
  },
  selectedColorOption: {
    borderWidth: 2,
    borderColor: '#a0522d',
  },
  sizeOption: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
    marginRight: 10,
  },
  selectedSizeOption: {
    borderColor: '#a0522d',
    backgroundColor: '#a0522d',
  },
  sizeOptionText: {
    fontSize: 14,
    color: '#333',
  },
  selectedSizeOptionText: {
    color: '#fff',
  },
  
  // Artisan Story
  productArtisanStory: {
    fontSize: 14,
    color: '#666',
    marginTop: 5,
    lineHeight: 20,
  },
  viewProfileText: {
    color: '#a0522d',
    fontSize: 14,
    marginTop: 5,
  },
  
  // Zoom Modal
  zoomModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomModalCloseButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 1,
  },
  zoomedImage: {
    width: width,
    height: height * 0.7,
  },

  // Cart Page Styles
  emptyCartContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyCartText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 16,
    marginBottom: 8,
  },
  emptyCartSubtext: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
  },
  continueShoppingButton: {
    backgroundColor: '#a0522d',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  continueShoppingText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  cartItemsContainer: {
    padding: 16,
  },
  cartItem: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cartItemImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    marginRight: 16,
  },
  cartItemDetails: {
    flex: 1,
    justifyContent: 'space-between',
  },
  cartItemName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  ratingText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 4,
    marginRight: 8,
  },
  reviewsText: {
    fontSize: 12,
    color: '#888',
  },
  artisanText: {
    fontSize: 12,
    color: '#C27D5E',
    marginBottom: 8,
    fontStyle: 'italic',
  },
  cartItemOption: {
    fontSize: 12,
    color: '#666',
    marginBottom: 2,
  },
  cartItemPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#a0522d',
    marginBottom: 12,
  },
  cartItemActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    borderRadius: 20,
    padding: 4,
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
  },
  quantityText: {
    fontSize: 14,
    fontWeight: '600',
    marginHorizontal: 12,
    minWidth: 20,
    textAlign: 'center',
  },
  removeButton: {
    padding: 8,
  },
  priceSummary: {
    backgroundColor: '#fff',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 16,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    paddingTop: 12,
    marginTop: 4,
  },
  priceLabel: {
    fontSize: 16,
    color: '#666',
  },
  priceValue: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  totalValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#a0522d',
  },
  cartFooter: {
    backgroundColor: '#fff',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  checkoutButton: {
    backgroundColor: '#A0522D',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  checkoutButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },

  // Checkout Page Styles
checkoutItem: {
  flexDirection: 'row',
  backgroundColor: '#fff',
  borderRadius: 8,
  marginBottom: 12,
  padding: 12,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 2,
},
checkoutItemImage: {
  width: 60,
  height: 60,
  borderRadius: 8,
  marginRight: 12,
},
checkoutItemDetails: {
  flex: 1,
  justifyContent: 'center',
},
checkoutItemName: {
  fontSize: 14,
  fontWeight: '600',
  color: '#333',
  marginBottom: 4,
},
checkoutItemPrice: {
  fontSize: 14,
  color: '#a0522d',
  fontWeight: '500',
},
paymentOption: {
  flexDirection: 'row',
  alignItems: 'center',
  padding: 16,
  borderBottomWidth: 1,
  borderBottomColor: '#f0f0f0',
},
paymentOptionSelected: {
  backgroundColor: '#f0f8ff',
},
paymentOptionText: {
  flex: 1,
  fontSize: 16,
  color: '#333',
  marginLeft: 16,
},
// My Orders Page Styles
ordersContainer: {
  padding: 16,
},
orderCard: {
  backgroundColor: '#fff',
  borderRadius: 12,
  marginBottom: 16,
  padding: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
orderHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  marginBottom: 16,
  paddingBottom: 16,
  borderBottomWidth: 1,
  borderBottomColor: '#F5DAC9',
},
orderId: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#333',
  marginBottom: 4,
},
orderDate: {
  fontSize: 14,
  color: '#666',
},
statusBadge: {
  paddingHorizontal: 12,
  paddingVertical: 6,
  borderRadius: 16,
},
statusText: {
  fontSize: 12,
  fontWeight: '600',
},
orderItem: {
  flexDirection: 'row',
  marginBottom: 16,
},
orderItemImage: {
  width: 80,
  height: 80,
  borderRadius: 8,
  marginRight: 12,
},
orderItemDetails: {
  flex: 1,
  justifyContent: 'center',
},
orderItemName: {
  fontSize: 16,
  fontWeight: '600',
  color: '#333',
  marginBottom: 4,
},
orderItemArtisan: {
  fontSize: 14,
  color: '#C27D5E',
  marginBottom: 4,
  fontStyle: 'italic',
},
orderItemPrice: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#a0522d',
},
orderFooter: {
  borderTopWidth: 1,
  borderTopColor: '#F5DAC9',
  paddingTop: 16,
  marginTop: 8,
},
orderTotal: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#333',
  marginBottom: 12,
  textAlign: 'right',
},
orderActions: {
  flexDirection: 'row',
  justifyContent: 'flex-end',
  gap: 12,
},
primaryButton: {
  backgroundColor: '#a0522d',
  paddingHorizontal: 20,
  paddingVertical: 10,
  borderRadius: 6,
},
primaryButtonText: {
  color: '#fff',
  fontSize: 14,
  fontWeight: '600',
},
secondaryButton: {
  borderWidth: 1,
  borderColor: '#a0522d',
  paddingHorizontal: 20,
  paddingVertical: 10,
  borderRadius: 6,
},
secondaryButtonText: {
  color: '#a0522d',
  fontSize: 14,
  fontWeight: '600',
},

// Returns Page Styles
returnsContainer: {
  padding: 16,
},
returnCard: {
  backgroundColor: '#fff',
  borderRadius: 12,
  marginBottom: 16,
  padding: 16,
  borderColor: '#FAECE0',
  borderWidth: 1,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
returnHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  marginBottom: 16,
  paddingBottom: 16,
  borderBottomWidth: 1,
  borderBottomColor: '#F5DAC9',
},
returnId: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#333',
  marginBottom: 2,
},
returnOrderId: {
  fontSize: 14,
  color: '#666',
  marginBottom: 4,
},
returnDate: {
  fontSize: 12,
  color: '#888',
},
returnStatusBadge: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 12,
  paddingVertical: 6,
  borderRadius: 16,
},
returnStatusText: {
  fontSize: 12,
  fontWeight: '600',
},
returnItem: {
  flexDirection: 'row',
  marginBottom: 16,
  paddingBottom: 16,
  borderBottomWidth: 1,
  borderBottomColor: '#F5DAC9',
},
returnItemImage: {
  width: 80,
  height: 80,
  borderRadius: 8,
  marginRight: 12,
},
returnItemDetails: {
  flex: 1,
  justifyContent: 'center',
},
returnItemName: {
  fontSize: 16,
  fontWeight: '600',
  color: '#333',
  marginBottom: 4,
},
returnItemArtisan: {
  fontSize: 14,
  color: '#C27D5E',
  marginBottom: 4,
  fontStyle: 'italic',
},
returnItemPrice: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#a0522d',
},
returnDetails: {
  marginBottom: 16,
},
detailRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  marginBottom: 8,
},
detailLabel: {
  fontSize: 14,
  color: '#666',
  fontWeight: '500',
},
detailValue: {
  fontSize: 14,
  color: '#333',
  flex: 1,
  marginLeft: 8,
  textAlign: 'right',
},
refundAmount: {
  fontWeight: 'bold',
  color: '#4CAF50',
},
returnActions: {
  flexDirection: 'row',
  justifyContent: 'flex-end',
  gap: 12,
},

// Artisan Profile Styles
artisanStats: {
  flexDirection: 'row',
  justifyContent: 'space-around',
  backgroundColor: '#fff',
  padding: 16,
  marginBottom: 16,
},
statItem: {
  alignItems: 'center',
},
statValue: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#a0522d',
  marginBottom: 4,
},
statLabel: {
  fontSize: 14,
  color: '#666',
},
techniqueTag: {
  backgroundColor: '#f0f8ff',
  paddingHorizontal: 12,
  paddingVertical: 6,
  borderRadius: 16,
  marginRight: 8,
  marginBottom: 8,
},
techniqueText: {
  color: '#a0522d',
  fontSize: 12,
  fontWeight: '500',
},
awardItem: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 12,
  backgroundColor: '#fffaf0',
  padding: 12,
  borderRadius: 8,
},
// ArtisanBlog Page Styles
  artisanBlogContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  artisanBlogContent: {
    flex: 1,
    padding: 16,
  },
  artisanProfileHeader: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  artisanProfileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  artisanProfileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginRight: 16,
  },
  artisanProfileDetails: {
    flex: 1,
  },
  artisanProfileName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  artisanProfileCraft: {
    fontSize: 16,
    color: '#a0522d',
    marginBottom: 4,
  },
  artisanProfileLocation: {
    fontSize: 14,
    color: '#666',
  },
  artisanStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    paddingTop: 16,
  },
  artisanStat: {
    alignItems: 'center',
  },
  artisanStatValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  artisanStatLabel: {
    fontSize: 14,
    color: '#666',
  },
  contentTabs: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    marginBottom: 16,
    padding: 4,
  },
  contentTab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
  },
  activeContentTab: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  contentTabText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
  },
  activeContentTabText: {
    color: '#a0522d',
    fontWeight: '600',
  },
  blogPostCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  blogPostImage: {
    width: '100%',
    height: 200,
  },
  blogPostContent: {
    padding: 16,
  },
  blogPostTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  blogPostDate: {
    fontSize: 12,
    color: '#888',
    marginBottom: 12,
  },
  blogPostExcerpt: {
    fontSize: 14,
    color: '#555',
    lineHeight: 20,
    marginBottom: 12,
  },
  blogPostReadMore: {
    color: '#a0522d',
    fontSize: 14,
    fontWeight: '500',
  },
  videoCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  videoThumbnail: {
    width: '100%',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  playButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoInfo: {
    padding: 16,
  },
  videoTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  videoDate: {
    fontSize: 12,
    color: '#888',
  },
  productShowcaseCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  showcaseTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  showcaseImage: {
    width: '100%',
    height: 200,
    borderRadius: 8,
    marginBottom: 12,
  },
  showcaseDescription: {
    fontSize: 14,
    color: '#555',
    lineHeight: 20,
  },
  emptyContent: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyContentText: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
    marginTop: 16,
  },
  // styles for Artisan Blog Page
    seeAllText: {
    fontSize: 14,
    color: '#a0522d',
    fontWeight: '500',
  },
  suggestionsList: {
    paddingHorizontal: 8,
  },
  videosList: {
    paddingHorizontal: 8,
  },
  artisanSuggestionCard: {
    width: 140,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  artisanSuggestionHeader: {
    alignItems: 'center',
  },
  artisanSuggestionImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginBottom: 12,
  },
  artisanSuggestionInfo: {
    alignItems: 'center',
  },
  artisanSuggestionName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
    textAlign: 'center',
  },
  artisanSuggestionCraft: {
    fontSize: 12,
    color: '#a0522d',
    marginBottom: 4,
    textAlign: 'center',
  },
  artisanSuggestionLocation: {
    fontSize: 11,
    color: '#666',
    textAlign: 'center',
  },
  // Short Videos Styles
  shortVideoCard: {
    width: 160,
    marginRight: 12,
  },
  videoThumbnailContainer: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 8,
  },
  shortVideoThumbnail: {
    width: 160,
    height: 240,
    borderRadius: 12,
  },
  videoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'space-between',
    padding: 8,
  },
  playIconContainer: {
    alignSelf: 'center',
    marginTop: 80,
  },
  videoDuration: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
    alignSelf: 'flex-end',
  },
  videoInfo: {
    paddingHorizontal: 4,
  },
  videoTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  videoViews: {
    fontSize: 12,
    color: '#666',
  },
  contentCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  contentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  contentArtisanImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 12,
  },
  contentArtisanInfo: {
    flex: 1,
  },
  contentArtisanName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  contentArtisanCraft: {
    fontSize: 12,
    color: '#666',
  },
  contentImage: {
    width: '100%',
    height: width,
  },
  videoContainer: {
    position: 'relative',
  },
  playButtonOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  captionPreview: {
    padding: 12,
  },
  captionText: {
    fontSize: 14,
    color: '#333',
    lineHeight: 18,
  },
  captionName: {
    fontWeight: '600',
  },
  shareMenu: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    padding: 8,
  },
  shareOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  shareIcon: {
    marginRight: 12,
    width: 24,
  },
  shareOptionText: {
    fontSize: 14,
    color: '#333',
  },
  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  modalBackButton: {
    padding: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  modalContent: {
    flex: 1,
  },
  modalArtisanInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  modalArtisanImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
  },
  modalArtisanDetails: {
    flex: 1,
  },
  modalArtisanName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  modalArtisanCraft: {
    fontSize: 14,
    color: '#666',
  },
  modalContentImage: {
    width: '100%',
    height: width,
  },
  modalVideoContainer: {
    position: 'relative',
  },
  modalPlayButton: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  postDetails: {
    padding: 16,
  },
  postTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  postDate: {
    fontSize: 14,
    color: '#666',
    marginBottom: 16,
  },
  postDescription: {
    fontSize: 16,
    color: '#333',
    lineHeight: 24,
  },
});

export default AppStyles;